import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
print("loding")


name = np.array(["mansingh", "jack", "lion", "jhon","max"])
day = np.array([10,11,12,13,15])
time = np.array([10,10,18,5,15])
sale= np.array([10000,20000,30000,1000,24000])
profit = np.array(sale + sale*.10)
salary = np.array([40000,50000, 30000, 45000,60000])
bonus = salary* 0.10 

df =pd.DataFrame({
    "name":name,
    "salary":  salary,
    "sale":sale,
    "day":day,
    "time":time,
    "bonus":bonus,
    "profit":profit
})

print(df)

df["name"]= name + " bhai"

df.insert(0, "emp_id", [101,102,103,104,105])
df.set_index("emp_id", inplace=True)
print(df)


"""
plt.figure(figsize=(14,8))
plt.plot(day,sale , color="red", linestyle="--", marker="*", linewidth=1)
plt.grid( True, color="black", linestyle=":")
plt.show()
"""
plt.figure(figsize=(14,8))

plt.subplot(2,2,1)
plt.title("salary chart ")
plt.bar(name, salary, color="red" , label="salary'")
plt.xlabel("name's  of employee ")
plt.ylabel("salary's of employees ")
plt.grid(True, linestyle=":",  linewidth=1.5)

plt.subplot(2,2,2)
plt.suptitle("this is chart is generated by  jack")
plt.title("work timing ")
plt.bar(name, time, color="red" , label="time'" )
plt.xlabel("name's  of employee ")
plt.ylabel("salary's of employees ")
plt.legend(loc="upper left", fontsize=10)
plt.grid(True, linestyle=":",linewidth=1.5)

plt.subplot(2,2,3)
plt.title("total sale")
plt.plot(day, profit, color="red" , label="sale'", marker="o" )
plt.plot(day, sale, color="black" , marker="o", )
plt.xlabel("name's  of employee ")
plt.ylabel("salary's of employees ")
plt.legend(loc="upper left", fontsize=15)
plt.grid(True, linestyle=":",  linewidth=1.5)

plt.subplot(2,2,4)
plt.title("total sale")
plt.scatter(day, profit, s=100, label="total",)
plt.legend(loc="upper right",fontsize=10)
plt.xlabel("name's  of employee ")
plt.ylabel("salary's of employees ")
plt.grid(True, linestyle=":",)

plt.tight_layout()
plt.show()